### PR TITLE
Python 3 Compatibility - Rebased Fork

### PR DESCRIPTION
**Pull request by rakanalh**
This PR is a rebase of @avendael's work on Python3 compatibility to the latest version of develop.

Thank you @geeknam, @avendael

### CODE REVIEW

**Comment by rakanalh** [comment]
@geeknam did you get the chance to review this?

**Comment by dotpot** [comment]
:+1:

**Comment by geeknam** [comment]
Thanks guys, can we get the coverage & health up? Who wants to volunteer to do this? :)

**Comment by rakanalh** [comment]
I believe the priority should be making a release rather than waiting for people to improve health indicator & tests. All current tests pass so the library should be good to go for a release with this branch.

This is my 0.02

**Comment by geeknam** [comment]
Thanks for your input @rakanalh. Landscape caught an undefined variable `urllib` https://landscape.io/diff/148815

**Comment by geeknam** [comment]
In my opinion, using `requests` and replacing urllib and urllib2 will definitely be a good move here.

Benefits:
- requests is python 3 compatible
- using requests would make the code cleaner
- everyone is familiar with requests, requests is more human friendly

**Comment by rakanalh** [comment]
I agree... but many people along with myself need this to be Py3 compliant as soon as possible.

As for requests, i also agree. I prefer using requests over urllib. Could you leave this as an open issue for someone to pick up and create a PR for that?

**Comment by geeknam** [comment]
https://github.com/geeknam/python-gcm/pull/60 fixes this

**Pull request closed without merging**
