### PR TITLE
Add Topic Messaging support

### PR DESCRIPTION
**Pull request by Kudo**
Reference #73 to add GCM [Topic Messaging](https://developers.google.com/cloud-messaging/topic-messaging)

Please help to review if the code or test are okay or not and feel free to give comments.
Thanks.

### CODE REVIEW

**Comment by Kudo** [comment]
Oops, sorry that GCM did not support to send both registration_id and topic.
Please stay tuned and let me update the PR.

**Comment by Kudo** [comment]
@geeknam I am sorry to introduce 2% healthy decrease.  I am trying my best to rewrite better.
However, there are some code from foundation and I am not able to rewrite at current stage.
Is current changes okay for you?

**Comment by geeknam** [comment]
Thanks dude, I'll review when I have some time.

On Tuesday, 1 September 2015, Kudo Chien <notifications@github.com> wrote:

> @geeknam <https://github.com/geeknam> I am sorry to introduce 2% healthy
> decrease. I am trying my best to rewrite better.
> However, there are some code from foundation and I am not able to rewrite
> at current stage.
> Is current changes okay for you?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/geeknam/python-gcm/pull/74#issuecomment-136667515>.
>


-- 
Regards,
Nam Ngo

**Comment by Kudo** [comment]
Thank you

**Comment by mnemonicflow** [comment]
Any updates on this?

**Comment by geeknam** [comment]
I've had a look at the code. It looks like we have some code duplication issues especially with the exponential backoff feature. Feel free to refactor it. @mnemonicflow will help out as he's been added as a contributor.

**Comment by geeknam** [comment]
Also conditionals in `construct_payload` could be solved with having a Payload class and some inheritance `class TopicPayload(BasePayload)`

**Comment by Kudo** [comment]
Thanks guys, I will take time to refactor the code once time is available.
Current plan is that as @geeknam mentioned to break Payload to another class and I plan to add builder for it, since there are too many option combinations.

Furthermore, just to confirm what is the use case of `plaintext_request()`?
`json_request()` can support all of the functionalities plus multiple registration id support.
If we can remove plaintext support, we can remove many code (as well as in test code).
However, that will bring an interface change.
How do you think?

**Comment by mnemonicflow** [comment]
@Kudo plaintext_request is one of the two MIME types usable in the Content-Type header defined for the HTTP protocol that is supported by the GCM servers.
For example, depending on what Content-Type header field value the HTTP client is using: **application/json** for JSON; and **application/x-www-form-urlencoded;charset=UTF-8** for plain text. If Content-Type is omitted, the format is assumed to be plain text. 

I think the reason for having plain text and JSON is twofold. 
Firstly, we have plain text support due to historical reasons. The plain text input format was simply added first in Android C2DM because it was more generally available, being very familiar to HTTP client-server interactions at that time. 
Secondly, it gives more flexibility in terms of what you need to implement as a client. Plain text is simply plain old HTTP POST, which every HTTP client out there should be able to know how to handle. Whereas, the JSON format means we also need to implement a JSON parser and generator (reader and writer) to be able to send requests and read back the responses.

**Comment by Kudo** [comment]
@mnemonicflow Thanks for your explain.  Well, maybe from my usage that simply use python-gcm as a GCM sender to send downstream message.
So callers don't care how the library internally transmit data to Google's GCM server which is either plaintext or JSON.

If the use case makes sense and fulfills most people's usage. Please consider this changes to clean the source code.
And the remain concern is about interface change to deprecate `plaintext_request()`.

**Comment by geeknam** [comment]
plaintext_request() was written for single messages (where you can only pass one registration id). I separated them into two methods to adhere to GCM docs back in the day.

The refactor can merge those two methods into one, it should be as simple as gcm.send() maybe.

**Comment by geeknam** [comment]
This might help:

https://github.com/geeknam/python-gcm/pull/80

**Comment by Kudo** [comment]
I've checked #80 which is cleaner.  I will update my code after #80 getting merged.
If there are anythings I can help, please feel free to let me know.
Thanks.

**Comment by mnemonicflow** [comment]
@Kudo You can start working on integrating the topic messaging feature as #80 has been merged into master.

**Comment by Kudo** [comment]
Thanks @geeknam @mnemonicflow.
The refactored `json_request()` and `plaintext_request()` use **kwargs.
Topic messages could send through the same way.
Unfortunately, GCM server will raise an error if callers send both `registration_ids` and `to` parameters.

We should have some hints for callers to send correct parameters.
I have two proposals.
First one is to add a function (e.g. topic_request() ) which code is similar with json_request() except we don't need registration_ids but to fill topic in `to` parameter.

The second one is aggressively refactoring to remove plaintext_request() and change to the following functions:
1. `send_downstream_message(registration_ids, data, **options)`
2. `send_topic_message(topic, data, **options)`
For future support
3. `send_device_group_message(notification_key, data, **options)`

I personally like the second one as mentioned before for my use case.
Please have some comments for me and I will try to update accordingly.

Thanks.

**Comment by mnemonicflow** [comment]
@Kudo We can add client side validation for each payload class using the validate method introduced by geeknam, but we have to have the same separate methods for each request type (plaintext, json, topic, device group) as we have now. We can probably add a convenience method `send` to help newcomers that are a bit confused by the plaintext and json divide.

The notification_key is deprecated and device group messaging uses the same 'to' key as the topic request.
I think we should reuse the json_request as much as possible and create a new topic_request method as you said, that just calls json_request and tell it to do some additional validation on the payload.
For the validation of the 'to' parameter when the topic_request method is called we can add a validate_to method to the JsonPayload class at runtime using something like this http://stackoverflow.com/questions/17929543/how-can-i-dynamically-create-class-methods-for-a-class-in-python

**Comment by mnemonicflow** [comment]
Maybe for some inspiration regarding topic messaging we can also have a look at this PR https://github.com/google/gcm/pull/116 which is being integrated in the official sample gcm repository

**Comment by mnemonicflow** [comment]
After thinking more about it I don't think it's feasable anymore to do what I previously said.

@Kudo I took your changes and resolved all the conflicts and submited a single commit as yourself in the 'topic_messaging' branch here: https://github.com/geeknam/python-gcm/commit/3f011a6a058fc8f4a6a12fa6fd04bbd35839d507

All the tests are running. Will have to test in live mode if the code for sending messages to a topic actually works.

**Comment by Kudo** [comment]
Dears,

I am in a business travel this week and please let me update next week.
Sorry for inconvenience.
Thank you.

**Comment by mnemonicflow** [comment]
I've tested the code in the topic_messaging branch and it seems to work:
```
[2015-10-18 23:15:26,011 - DEBUG - gcm.py:231 - log()] Added a stderr logging handler to logger: gcm.gcm
[2015-10-18 23:15:26,012 - DEBUG - gcm.py:231 - log()] Added a stderr logging handler to logger: requests.packages.urllib3
[2015-10-18 23:15:26,012 - DEBUG - gcm.py:231 - log()] Request URL: https://gcm-http.googleapis.com/gcm/send
[2015-10-18 23:15:26,012 - DEBUG - gcm.py:231 - log()] Request headers: {'Authorization': 'key=xyz', 'Content-Type': 'application/json'}
[2015-10-18 23:15:26,012 - DEBUG - gcm.py:231 - log()] Request proxy: None
[2015-10-18 23:15:26,012 - DEBUG - gcm.py:231 - log()] Request timeout: None
[2015-10-18 23:15:26,012 - DEBUG - gcm.py:231 - log()] Request data: {"to": "/topics/089e94bf8ffef5d8b5d0293f3c184677c556a7dd", "data": {"param1": "value1", "param2": "value2"}}
[2015-10-18 23:15:26,012 - DEBUG - gcm.py:231 - log()] Request is_json: True
[2015-10-18 23:15:26,018 - INFO - connectionpool.py:756 - _new_conn()] Starting new HTTPS connection (1): gcm-http.googleapis.com
[2015-10-18 23:15:26,324 - DEBUG - connectionpool.py:387 - _make_request()] "POST /gcm/send HTTP/1.1" 200 None
[2015-10-18 23:15:26,328 - DEBUG - gcm.py:231 - log()] Response status: 200 OK
[2015-10-18 23:15:26,329 - DEBUG - gcm.py:231 - log()] Response headers: {'X-Frame-Options': 'SAMEORIGIN', 'Content-Encoding': 'gzip', 'Cache-Control': 'private, max-age=0', 'Server': 'GSE', 'Expires': 'Sun, 18 Oct 2015 20:15:26 GMT', 'Date': 'Sun, 18 Oct 2015 20:15:26 GMT', 'Alt-Svc': 'quic=":443"; p="1"; ma=604800', 'X-Content-Type-Options': 'nosniff', 'X-XSS-Protection': '1; mode=block', 'Content-Type': 'application/json; charset=UTF-8', 'Transfer-Encoding': 'chunked', 'Alternate-Protocol': '443:quic,p=1'}
[2015-10-18 23:15:26,329 - DEBUG - gcm.py:231 - log()] Response data: {"message_id":6564672020888395646}
```

using the following code:
```
#!/usr/bin/env python3

from gcm import GCM

# Topic Messaging
gcm = GCM('xyz', debug=True)
data = {'param1': 'value1', 'param2': 'value2'}
topic = '089e94bf8ffef5d8b5d0293f3c184677c556a7dd'
gcm.send_topic_message(topic=topic, data=data)
```

**Comment by Kudo** [comment]
Dears,

Sorry for late.
I just do real test on Android simulator and it works fine.
Please check the attached image.
Thank for all your work and if there are anything I can help, please feel free to let me know.

screen shot 2015-10-24 at 1 02 28 am

screen shot 2015-10-24 at 1 05 10 am

**Comment by mnemonicflow** [comment]
@Kudo Thanks! Merged in #90

**Pull request closed without merging**
