### PR TITLE
python3 compatibility

### PR DESCRIPTION
**Pull request by avendael**
Hello. I modified python-gcm a bit to make it compatible with python3. All tests have passed for both python2.7 and python3.3. I hope this helps.

### CODE REVIEW

**Comment by rakanalh** [comment]
@geeknam, any chance this could be merged?

**Comment by geeknam** [comment]
Hey guys, I'm keen on getting this merged. It would be awesome if someone could update this PR so I can cleanly merge it. Any volunteers?

**Comment by rakanalh** [comment]
I am. I'll rebase the branch over the new master and create a new PR for this. Will be ready tomorrow :)

**Comment by dkovalkov** [comment]
I need  python 3 compliant version also. Thank you.

**Comment by geeknam** [comment]
In my opinion, using `requests` and replacing urllib and urllib2 will definitely be a good move here.

Benefits:
- requests is python 3 compatible
- using requests would make the code cleaner
- everyone is familiar with requests, requests is more human friendly

**Comment by geeknam** [comment]
https://github.com/geeknam/python-gcm/pull/60 fixes this

**Pull request closed without merging**
